using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;

namespace PersonalFinanceManager.Infrastructure.Data;

public static class DatabaseInitializer
{
	/// <summary>
	/// Ensures the database is created and schema matches the current model.
	/// In Development: uses EnsureCreated() to auto-create tables.
	/// In Production: use the SQL script generated by ExportCreateScript().
	/// </summary>
	public static async Task InitializeDatabaseAsync(IServiceProvider serviceProvider, bool isDevelopment)
	{
		using var scope = serviceProvider.CreateScope();
		var context = scope.ServiceProvider.GetRequiredService<AppDBContext>();
		var logger = scope.ServiceProvider.GetRequiredService<ILogger<AppDBContext>>();

		try
		{
			if (isDevelopment)
			{
				logger.LogInformation("Development mode — ensuring database is created...");

				// EnsureCreated creates the DB and all tables from the current model
				// NOTE: This does NOT support incremental migrations.
				// If you change the model, drop and recreate the DB during development.
				var created = await context.Database.EnsureCreatedAsync();

				if (created)
					logger.LogInformation("Database was created successfully.");
				else
					logger.LogInformation("Database already exists.");
			}
			else
			{
				logger.LogInformation("Production mode — checking database connectivity...");
				var canConnect = await context.Database.CanConnectAsync();

				if (!canConnect)
					throw new InvalidOperationException(
						"Cannot connect to the database. Ensure migrations have been applied using the SQL script.");

				logger.LogInformation("Database connection verified.");
			}
		}
		catch (Exception ex)
		{
			logger.LogError(ex, "An error occurred while initializing the database.");
			throw;
		}
	}

	/// <summary>
	/// Generates the full CREATE TABLE SQL script from the current EF model.
	/// Use this to produce a migration script for production deployments.
	/// </summary>
	public static string ExportCreateScript(IServiceProvider serviceProvider)
	{
		using var scope = serviceProvider.CreateScope();
		var context = scope.ServiceProvider.GetRequiredService<AppDBContext>();
		return context.Database.GenerateCreateScript();
	}

	/// <summary>
	/// Drops and recreates the database. USE ONLY IN DEVELOPMENT
	/// when entity models change and you need a fresh schema.
	/// </summary>
	public static async Task ResetDatabaseAsync(IServiceProvider serviceProvider)
	{
		using var scope = serviceProvider.CreateScope();
		var context = scope.ServiceProvider.GetRequiredService<AppDBContext>();
		var logger = scope.ServiceProvider.GetRequiredService<ILogger<AppDBContext>>();

		logger.LogWarning("Dropping and recreating the database...");

		await context.Database.EnsureDeletedAsync();
		await context.Database.EnsureCreatedAsync();

		logger.LogWarning("Database has been reset successfully.");
	}
}
